THREADS_PER_JOB: 16

SOURCE: "source"

# Pomoxis
IN_POMOXIS: "~/git/pomoxis/venv/bin/activate"

# Scrappie 
SCRAPPIE: "~/git/scrappie"
SCRAPPIE_OPTS: 
    "": "raw --model rgrgr_r94 --uuid"
    "_hp": "raw -H mean --model rgrgr_r94 --uuid"

        
# Flappie 
FLAPPIE: "~/git/github/flappie"
FLAPPIE_OPTS: 
    "": "raw --model rgrgr_r94 --uuid"
    "_r10c_pcr": "--model=r10c_pcr"

        
# Guppy
GUPPY: "/usr/bin/guppy_basecaller"
GUPPY_OPTS: 
    "": "-c dna_r9.4_450bps.cfg"
    "_hp": "-c dna_r9.4_450bps.cfg --hp_correct 1"

GUPPY_SLOTS: 20 

# subsample_bam
SUBSAMPLE_BAM_OPTS:
    "": ""
    "_prop": "--proportional"
 

#Canu 
CANU_EXEC: "~/git/canu-1.7.1/Linux-amd64/bin/canu"
CANU_EXEC_OPTS: "useGrid=False"
CANU_GENOME_SIZE: "4.8M"
CANU_OPTS:
    "": "" 

# Mini_assemble
MINI_ASSEMBLE_OPTS: 
    "": ""
    "_ce": "-c -e 10"
    "_ces": "-c -e 10 -n 10"
    "_ce3x_ecoli": "-c -e 3x -l 4.66mb"
    "_ce3x_yeast": "-c -e 3x -l 12.15mb"
    "_ce3x_lbrevis": "-c -e 3x -l 2.29mb"
    "_ce3xs_ecoli": "-c -e 3x -l 4.66mb -n 10"


# Nanopolish
NANOPOLISH: "~/git/nanopolish" 
# wildcards in dynamic files cannot be constrained => we can't safely extract a
# suffix from dynamic nanopolish targets to use to use nested config
NANOPOLISH_OPTS: "--fix-homopolymers"

# Medaka
IN_MEDAKA: "~/git/medaka/venv/bin/activate"
MEDAKA_OPTS: 
    "": ""

# Medaka training features
MEDAKA_TRAIN_FEAT_OPTS:
    "": "--chunk_len 1000 --chunk_ovlp 10 --batch_size 100"

MEDAKA_TRAIN_OPTS:
    "": "--mini_epochs 5 --validation_split 0.10"


# Ray
IN_RAY: "~/git/ray/venv/bin/activate"

# assess_assembly
ASSESS_ASSM_OPTS: "-C"


# This has to be set for any assessment of consensus accuracy. 
TRUTH:
    "/nfs/groups_ech/res_data/active/refs/git_references/ecoli/ecoli_SCS110.fasta"

BASECALLER: "guppy" 

# reference to be used for each region set
REFERENCES: 
    "": "ref.fasta"
    "ecoli": "/nfs/groups_ech/res_data/active/refs/git_references/ecoli/ecoli_SCS110.fasta"
    "yeast": "/nfs/groups_ech/res_data/active/refs/git_references/yeast/yeast_S288C.fasta"
    "lbrevis": "/nfs/groups_ech/res_data/stored/datasets/apps_atcc_genomes/analysis/demultiplexed/refs_for_assembly/NC_008497.1.fa"

# regions used for subsampling
REGION_DEFINITIONS:
    "ecoli": "ecoli_SCS110_chromosome"
    "yeast": "yeast_S288C_chromosomeI yeast_S288C_chromosomeII yeast_S288C_chromosomeIII yeast_S288C_chromosomeIV yeast_S288C_chromosomeV yeast_S288C_chromosomeVI yeast_S288C_chromosomeVII yeast_S288C_chromosomeVIII yeast_S288C_chromosomeIX yeast_S288C_chromosomeX yeast_S288C_chromosomeXI yeast_S288C_chromosomeXII yeast_S288C_chromosomeXIII yeast_S288C_chromosomeXIV yeast_S288C_chromosomeXV yeast_S288C_chromosomeXVI"
    "lbrevis": "NC_008497.1"

# train on these region names (these must be keys for REGION_DEFINITIONS, REFERENCES and RUNIDS)
MEDAKA_TRAIN_REGIONS: ["yeast", "lbrevis"]

# Run a training replicate for each of these suffixes
MEDAKA_TRAIN_REPLICATES:
    ["rep_1", "rep_2", "rep_3"]

# Define runs - fast5s should be under ./runid/reads/ and can be in subdirectories.
RUNIDS:
    "yeast": ["80a94504", "f81e9478", "fad5950a"]
    "lbrevis": ["95730659", "15e93eaf", "c50fb4ef"]

# create sets of basecalls, assemblies and training features for these depths. 
# medaka models do not perform well (and can make consensus accuracy worse than
# the draft) for depths they were not exposed to during training. 
DEPTHS:
    [25, 50, 70, 100, 125, 150, 175, 200, 225, 250]
