THREADS_PER_JOB: 16

SOURCE: "source"

# Pomoxis
IN_POMOXIS: "~/git/pomoxis/venv/bin/activate"

# Scrappie 
SCRAPPIE: "~/git/scrappie"
SCRAPPIE_OPTS: 
    "": "raw --model rgrgr_r94 --uuid"
    "_hp": "raw -H mean --model rgrgr_r94 --uuid"

        
# Guppy
GUPPY: "/usr/bin/guppy_basecaller"
GUPPY_OPTS: 
    "": "-c dna_r9.4_450bps.cfg"
    "_hp": "-c dna_r9.4_450bps.cfg --hp_correct 1"

GUPPY_SLOTS: 4 

# subsample_bam
SUBSAMPLE_BAM_OPTS:
    "": ""
    "_prop": "--proportional"
 

#Canu 
CANU_EXEC: "~/git/canu-1.7.1/Linux-amd64/bin/canu"
CANU_EXEC_OPTS: "useGrid=False"
CANU_GENOME_SIZE: "4.8M"
CANU_OPTS:
    "": "" 

# Mini_assemble
MINI_ASSEMBLE_OPTS: 
    "": ""
    "_ce": "-c -e 10"
    "_ces": "-c -e 10 -n 10"
    "_ce3x_ecoli": "-c -e 3x -l 4.66mb"
    "_ce3x_yeast": "-c -e 3x -l 12.15mb"
    "_ce3x_lbrevis": "-c -e 3x -l 2.29mb"


# Nanopolish
NP: "~/git/nanopolish" 
# wildcards in dynamic files cannot be constrained => we can't safely extract a
# suffix from dynamic nanopolish targets to use to use nested config
NP_OPTS: "--fix-homopolymers"

# Medaka
IN_MEDAKA: "~/git/medaka_dev/venv/bin/activate"
MEDAKA_OPTS: 
    "": ""

# Medaka training features
MEDAKA_TRAIN_FEAT_OPTS:
    "": "--chunk_len 1000 --chunk_ovlp 10 --batch_size 100 --max_label_len 1 --model /nfs/groups_ech/res_data/active/mwykes/R10_ONLP13701/feature_set_30.yml"


# Miyagi
IN_MIYAGI: "~/git/miyagi/venv/bin/activate"
MIYAGI_BATCHES_PER_REF_MB: 100
MIYAGI_SCORE_READS_OPTS: "--pore_mode r94 --debug"
MIYAGI_APPLY_MODEL_OPTS: ""
MIYAGI_HOMOP_VCF_OPTS: ""

# Ray
IN_RAY: "~/git/ray/venv/bin/activate"

# assess_assembly
ASSESS_ASSM_OPTS: "-C"

# input paths
REFERENCE: "ref.fasta"
READS: "reads"

# Parameters only used in short cut target (e.g. standard_assm_polish)
BASECALLER: "scrappie"  
