THREADS_PER_JOB: 16

SOURCE: "source"

# Pomoxis
IN_POMOXIS: "~/git/pomoxis/venv/bin/activate"

# Scrappie 
SCRAPPIE: "~/git/scrappie"
SCRAPPIE_OPTS: 
    "": "raw --model rgrgr_r94 --uuid"
    "_hp": "raw -H mean --model rgrgr_r94 --uuid"

        
# Flappie 
FLAPPIE: "~/git/github/flappie"
FLAPPIE_OPTS: 
    "": "raw --model rgrgr_r94 --uuid"
    "_r10c_pcr": "--model=r10c_pcr"

        
# Guppy
GUPPY: "/usr/bin/guppy_basecaller"
GUPPY_OPTS: 
    "": "-c dna_r9.4_450bps.cfg"
    "_hp": "-c dna_r9.4_450bps.cfg --hp_correct 1"

GUPPY_SLOTS: 20 

# subsample_bam
SUBSAMPLE_BAM_OPTS:
    "": " --all_fail"
    "_prop": "--proportional --all_fail"
 

#Canu 
CANU_EXEC: "~/git/canu-1.7.1/Linux-amd64/bin/canu"
CANU_EXEC_OPTS: "useGrid=False"
CANU_OPTS:
    "": "" 

# Mini_assemble
MINI_ASSEMBLE_OPTS: 
    "": ""
    "_ce": "-c -e 10"
    "_ces": "-c -e 10 -n 10"
    "_ce3x_ecoli": "-c -e 3x -l 4.66mb"
    "_ce3x_yeast": "-c -e 3x -l 12.15mb"
    "_ce3x_lbrevis": "-c -e 3x -l 2.29mb"
    "_ce3xs_ecoli": "-c -e 3x -l 4.66mb -n 10"
    "_ce3x_BS.pilon.polished.v3.ST170922": "-c -e 3x -l 4mb"
    "_ce3x_Enterococcus_faecalis_complete_genome": "-c -e 3x -l 2.8mb"
    "_ce3x_Escherichia_coli_chromosome": "-c -e 3x -l 4.8mb"
    "_ce3x_Lactobacillus_fermentum_complete_genome": "-c -e 3x -l 1.9mb"
    "_ce3x_Pseudomonas_aeruginosa_complete_genome": "-c -e 3x -l 6.8mb"
    "_ce3x_Staphylococcus_aureus_chromosome": "-c -e 3x -l 2.7mb"


# Nanopolish
NANOPOLISH: "~/git/nanopolish" 
# wildcards in dynamic files cannot be constrained => we can't safely extract a
# suffix from dynamic nanopolish targets to use to use nested config
NANOPOLISH_OPTS: "--fix-homopolymers"

# Medaka
IN_MEDAKA: "~/git/medaka/venv/bin/activate"
MEDAKA_OPTS: 
    "": ""

# Medaka training features
MEDAKA_TRAIN_FEAT_OPTS:
    "": "--chunk_len 1000 --chunk_ovlp 10 --batch_size 100"

MEDAKA_TRAIN_OPTS:
    "": "--mini_epochs 5 --validation_split 0.10"


# Ray
IN_RAY: "~/git/ray/venv/bin/activate"

# assess_assembly
ASSESS_ASSM_OPTS: "-C"


# This has to be set for any assessment of consensus accuracy. 
TRUTH:
    "/nfs/groups_ech/res_data/active/refs/git_references/ecoli/ecoli_SCS110.fasta"

BASECALLER: "guppy" 

# reference to be used for each region set
REFERENCES: 
    "": "ref.fasta"
    "zymo": "/media/groups_cs2/res_data/active/refs/ZymoBIOMICS.STD.refseq.v2/all_species.fasta"

# regions used for subsampling - each region in each list of regions will be subsampled and assembled separately. 
TRAIN_REGION_DEFINITIONS: 
    "zymo": ["BS.pilon.polished.v3.ST170922", 
             "Enterococcus_faecalis_complete_genome", 
             "Escherichia_coli_chromosome", 
             "Lactobacillus_fermentum_complete_genome", 
             "Pseudomonas_aeruginosa_complete_genome",
             "Staphylococcus_aureus_chromosome",
    ]
EVAL_REGION_DEFINITIONS: 
    "zymo": ["BS.pilon.polished.v3.ST170922", 
             "Enterococcus_faecalis_complete_genome", 
             "Escherichia_coli_chromosome", 
             "Lactobacillus_fermentum_complete_genome", 
             "Pseudomonas_aeruginosa_complete_genome",
             "Staphylococcus_aureus_chromosome",
             "Listeria_monocytogenes_complete_genome",
             "Salmonella_enterica_complete_genome",
    ]

# canu needs to know estimated genome sizes
REGION_LENGTHS:
    {
        "BS.pilon.polished.v3.ST170922": "4.0M",
        "Enterococcus_faecalis_complete_genome": "2.8M",
        "Escherichia_coli_chromosome": "4.9M",
        "Lactobacillus_fermentum_complete_genome": "1.9M",
        "Pseudomonas_aeruginosa_complete_genome": "6.8M",
        "Staphylococcus_aureus_chromosome": "2.7M",
        "Listeria_monocytogenes_complete_genome": "3.0M",
        "Salmonella_enterica_complete_genome": "4.8M",
    }


# train on these region names (these must be keys for REGION_DEFINITIONS, REFERENCES and RUNIDS)
MEDAKA_TRAIN_REGIONS: ["zymo"]
# train on these region names (these must be keys for REGION_DEFINITIONS, REFERENCES and RUNIDS)
MEDAKA_EVAL_REGIONS: ["zymo"]

# Run a training replicate for each of these suffixes
MEDAKA_TRAIN_REPLICATES:
    ["rep_1", "rep_2", "rep_3"]


# Define runs - fast5s should be under ./runid/reads/ and can be in subdirectories.
RUNIDS:
  #zymo: ['0b11bceb', '893d8c5f', '9a456918', 'ddfc392d', 'e49ace80', 'ef0bab84']
  zymo: ['loman',]

# create sets of basecalls, assemblies and training features for these depths. 
# medaka models do not perform well (and can make consensus accuracy worse than
# the draft) for depths they were not exposed to during training. 
DEPTHS:
    [25, 50, 70, 100, 125, 150, 175, 200]
