THREADS_PER_JOB: 16

SOURCE: "source"

# Pomoxis
IN_POMOXIS: "~/git/pomoxis/venv/bin/activate"

# Scrappie 
SCRAPPIE: "~/git/scrappie"
SCRAPPIE_OPTS: 
    "": "raw --model rgrgr_r94 --uuid"
    "_hp": "raw -H mean --model rgrgr_r94 --uuid"

        
# Flappie 
FLAPPIE: "~/git/github/flappie"
FLAPPIE_OPTS: 
    "": "raw --model rgrgr_r94 --uuid"
    "_r10c_pcr": "--model=r10c_pcr"

        
# Guppy
GUPPY: "/usr/bin/guppy_basecaller"
GUPPY_OPTS: 
    "": "-c dna_r9.4_450bps.cfg"
    "_hp": "-c dna_r9.4_450bps.cfg --hp_correct 1"

GUPPY_SLOTS: 4 

# subsample_bam
SUBSAMPLE_BAM_OPTS:
    "": ""
    "_prop": "--proportional"
 

#Canu 
CANU_EXEC: "~/git/canu-1.7.1/Linux-amd64/bin/canu"
CANU_EXEC_OPTS: "useGrid=False"
CANU_GENOME_SIZE: "4.8M"
CANU_OPTS:
    "": "" 

# Mini_assemble
MINI_ASSEMBLE_OPTS: 
    "": ""
    "_ce": "-c -e 10"
    "_ces": "-c -e 10 -n 10"

# Nanopolish
NANOPOLISH: "~/git/nanopolish" 
# wildcards in dynamic files cannot be constrained => we can't safely extract a
# suffix from dynamic nanopolish targets to use to use nested config
NANOPOLISH_OPTS: "--fix-homopolymers"

# Medaka
IN_MEDAKA: "~/git/medaka/venv/bin/activate"
MEDAKA_OPTS: 
    "": ""

# Medaka training features
MEDAKA_TRAIN_FEAT_OPTS:
    "": "--chunk_len 1000 --chunk_ovlp 10 --batch_size 100"


# Ray
IN_RAY: "~/git/ray/venv/bin/activate"

# assess_assembly
ASSESS_ASSM_OPTS: "-C"

# input paths
REFERENCE: "ref.fasta"
READS: "reads"

# Parameters only used in short cut target (e.g. standard_assm_polish)
BASECALLER: "scrappie"  
