THREADS_PER_JOB: 16

SOURCE: "source"

# Pomoxis
IN_POMOXIS: "~/git/pomoxis/venv/bin/activate"

# Scrappie 
SCRAPPIE: "~/git/scrappie"
SCRAPPIE_OPTS: "raw -H mean --model rgrgr_r94 --local 10.0 --uuid"

#Canu 
CANU_EXEC: "~/git/canu-1.7.1/Linux-amd64/bin/canu"
CANU_EXEC_OPTS: "useGrid=False"
CANU_GENOME_SIZE: "4.8M"

# Mini_assemble
MINI_ASSEMBLE_OPTS: ""

# Guppy
GUPPY: "/usr/bin/guppy_basecaller"
GUPPY_OPTS: "-c /opt/ont/guppy/data/dna_r9.4_450bps.cfg"
GUPPY_SLOTS: 4 

# Nanopolish
NP: "~/git/nanopolish" 
NP_OPTS: "--fix-homopolymers"

# Medaka
IN_MEDAKA: "~/git/medaka/venv/bin/activate"
MEDAKA_OPTS: 
  "": ""

# Miyagi
IN_MIYAGI: "~/git/miyagi/venv/bin/activate"
MIYAGI_BATCHES_PER_REF_MB: 100
MIYAGI_SCORE_READS_OPTS: "--pore_mode r94 --debug"
MIYAGI_APPLY_MODEL_OPTS: ""
MIYAGI_HOMOP_VCF_OPTS: ""

# Ray
IN_RAY: "~/git/ray/venv/bin/activate"

# assess_assembly
ASSESS_ASSM_OPTS: "-C"

# input paths
REFERENCE: "ref.fasta"
READS: "reads"

# Parameters only used in short cut target (e.g. standard_assm_polish)
BASECALLER: "scrappie"  
